# Generated by Django 3.2.6 on 2021-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetUps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='victor.nkuna@webmaster.co.za', max_length=254),
        ),
    ]
